export type PostType = 'static' | 'carousel' | 'story' | 'reels';
export type PostFormat = 'square' | 'vertical' | 'story';
export type PostStatus = 'draft' | 'scheduled' | 'published';
export type PostMonth = 'dezembro' | 'janeiro' | 'fevereiro' | 'marco';

export interface PostSlide {
  id: number;
  content: string;
  subContent?: string;
}

export interface PostData {
  id: number;
  slug: string;
  title: string;
  type: PostType;
  format: PostFormat;
  slides?: PostSlide[];
  date: string;
  time: string;
  boost: number | null;
  caption: string;
  cta: string;
  hashtags: string[];
  category: 'teaser' | 'launch' | 'feature' | 'social-proof' | 'seasonal' | 'b2b' | 'branding' | 'engagement' | 'ugc';
  month: PostMonth;
  status: PostStatus;
}

export const posts: PostData[] = [
  // =============================================
  // DEZEMBRO 2025 - LANCAMENTO
  // =============================================

  // SEMANA 1: TEASER (10-13 DEZ)
  {
    id: 1,
    slug: 'teaser-countdown',
    title: 'Countdown Teaser',
    type: 'story',
    format: 'story',
    slides: [
      { id: 1, content: 'Cansado de sorteios problematicos?' },
      { id: 2, content: 'Casal que tira casal.', subContent: 'Mesma pessoa do ano passado.' },
      { id: 3, content: 'A solucao chega em 3 dias...' },
    ],
    date: '10/12/2025',
    time: '19h',
    boost: null,
    caption: 'Algo novo esta chegando...',
    cta: 'Link na bio para waitlist',
    hashtags: ['#AmigoSecreto', '#Natal2025', '#EmBreve'],
    category: 'teaser',
    month: 'dezembro',
    status: 'draft',
  },
  {
    id: 2,
    slug: 'problemas-amigo-secreto',
    title: '5 Problemas do Amigo Secreto',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: '5 problemas que arruinam seu Amigo Secreto' },
      { id: 2, content: '1. Casal tira casal - de novo' },
      { id: 3, content: '2. Voce tira a mesma pessoa do ano passado' },
      { id: 4, content: '3. Ninguem sabe o que a pessoa quer' },
      { id: 5, content: '4. Alguem sempre descobre antes da hora', subContent: 'E se existisse uma solucao?' },
    ],
    date: '11/12/2025',
    time: '12h',
    boost: 100,
    caption: 'Todo ano a mesma historia: sorteio problematico, presentes errados, segredo vazado. E se existisse uma forma inteligente de resolver TODOS esses problemas?',
    cta: 'Quer saber primeiro? Link na bio',
    hashtags: ['#AmigoSecreto', '#NatalEmFamilia', '#Confraternizacao', '#ProblemasDeNatal', '#DicasDeNatal'],
    category: 'teaser',
    month: 'dezembro',
    status: 'draft',
  },
  {
    id: 3,
    slug: 'revelacao-marca',
    title: 'Revelacao da Marca',
    type: 'reels',
    format: 'story',
    slides: [
      { id: 1, content: 'O problema...' },
      { id: 2, content: 'A solucao...' },
      { id: 3, content: 'O Amigo Secreto', subContent: 'Seu amigo secreto, sem complicacao' },
    ],
    date: '12/12/2025',
    time: '18h',
    boost: 150,
    caption: 'Apresentamos O AMIGO SECRETO - o app que vai transformar sua brincadeira favorita de fim de ano.',
    cta: 'Cadastre-se na waitlist - Link na bio',
    hashtags: ['#OAmigoSecreto', '#AppNovo', '#Lancamento', '#Natal2025', '#AmigoSecretoApp'],
    category: 'launch',
    month: 'dezembro',
    status: 'draft',
  },

  // SEMANA 2: LANCAMENTO (14-18 DEZ)
  {
    id: 4,
    slug: 'lancamento',
    title: 'Lancamento Oficial',
    type: 'static',
    format: 'square',
    date: '14/12/2025',
    time: '10h',
    boost: 200,
    caption: 'O momento chegou! O Amigo Secreto esta DISPONIVEL para download.',
    cta: 'Baixe agora - Link na bio',
    hashtags: ['#OAmigoSecreto', '#DownloadAgora', '#AppGratis', '#Natal2025'],
    category: 'launch',
    month: 'dezembro',
    status: 'draft',
  },
  {
    id: 5,
    slug: 'feature-algoritmo',
    title: 'Feature: Algoritmo Inteligente',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: 'Nosso sorteio e INTELIGENTE' },
      { id: 2, content: 'Define restricoes:', subContent: 'Maria nao pode tirar Joao (sao casados)' },
      { id: 3, content: 'O algoritmo calcula TODAS as possibilidades' },
      { id: 4, content: 'Resultado: sorteio perfeito que respeita TODAS as regras' },
    ],
    date: '15/12/2025',
    time: '19h',
    boost: null,
    caption: 'Chega de sorteio manual com papelzinho. Nosso algoritmo anti-ciclos garante sorteio perfeito!',
    cta: 'Experimente gratis - Link na bio',
    hashtags: ['#AmigoSecreto', '#SorteioInteligente', '#Tecnologia', '#AlgoritmoInteligente'],
    category: 'feature',
    month: 'dezembro',
    status: 'draft',
  },
  {
    id: 6,
    slug: 'feature-wishlist',
    title: 'Feature: Wishlist',
    type: 'reels',
    format: 'story',
    slides: [
      { id: 1, content: 'Nunca mais erre o presente' },
      { id: 2, content: 'Cada participante cria sua lista' },
      { id: 3, content: 'Veja sugestoes de onde comprar' },
      { id: 4, content: 'Precos de varios marketplaces' },
    ],
    date: '16/12/2025',
    time: '12h',
    boost: null,
    caption: 'WISHLIST + VITRINE DE PRESENTES. Presente certo, garantido!',
    cta: 'Crie sua wishlist - Link na bio',
    hashtags: ['#ListaDeDesejos', '#Wishlist', '#PresentePerfeito', '#MelhorPreco', '#AmigoSecreto'],
    category: 'feature',
    month: 'dezembro',
    status: 'draft',
  },
  {
    id: 7,
    slug: 'feature-chat',
    title: 'Feature: Chat Anonimo',
    type: 'static',
    format: 'square',
    date: '17/12/2025',
    time: '19h',
    boost: null,
    caption: 'CHAT ANONIMO. De dicas sobre o presente sem revelar sua identidade.',
    cta: 'Comece a trocar mensagens - Link na bio',
    hashtags: ['#ChatSecreto', '#AmigoSecreto', '#MensagemAnonima', '#Surpresa', '#Segredo'],
    category: 'feature',
    month: 'dezembro',
    status: 'draft',
  },
  {
    id: 8,
    slug: 'feature-grupos',
    title: 'Feature: Grupos Ilimitados',
    type: 'story',
    format: 'story',
    slides: [
      { id: 1, content: 'Familia da Mamae' },
      { id: 2, content: 'Galera do Trabalho' },
      { id: 3, content: 'Amigos da Facul', subContent: 'GRUPOS ILIMITADOS - GRATIS' },
    ],
    date: '18/12/2025',
    time: '12h',
    boost: null,
    caption: 'Um app, todos os seus grupos. Familia. Trabalho. Amigos. Quantos voce quiser. E GRATIS.',
    cta: 'Crie seus grupos - Link na bio',
    hashtags: ['#GruposIlimitados', '#Familia', '#Trabalho', '#Amigos', '#AmigoSecreto'],
    category: 'feature',
    month: 'dezembro',
    status: 'draft',
  },

  // SEMANA 3: SOCIAL PROOF (19-23 DEZ)
  {
    id: 9,
    slug: 'tutorial-rapido',
    title: 'Tutorial Rapido',
    type: 'reels',
    format: 'story',
    slides: [
      { id: 1, content: 'Amigo Secreto em 60 segundos' },
      { id: 2, content: '1. Baixe o app' },
      { id: 3, content: '2. Crie um grupo' },
      { id: 4, content: '3. Convide por link ou QR code' },
      { id: 5, content: '4. Defina restricoes' },
      { id: 6, content: '5. Clique em sortear' },
      { id: 7, content: 'Pronto! Cada um ve apenas seu sorteado' },
    ],
    date: '19/12/2025',
    time: '18h',
    boost: 100,
    caption: 'TUTORIAL: Como organizar seu Amigo Secreto em menos de 1 minuto.',
    cta: 'Salve e compartilhe!',
    hashtags: ['#Tutorial', '#ComoFazer', '#AmigoSecreto', '#DicaRapida', '#Natal2025'],
    category: 'social-proof',
    month: 'dezembro',
    status: 'draft',
  },
  {
    id: 10,
    slug: 'depoimentos',
    title: 'Depoimentos',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: '"Finalmente minha sogra nao tirou meu sogro!"', subContent: '- Ana, 34' },
      { id: 2, content: '"Usei pro amigo secreto da empresa com 50 pessoas!"', subContent: '- Carlos, RH' },
      { id: 3, content: '"A wishlist salvou minha vida!"', subContent: '- Mariana, 28' },
    ],
    date: '20/12/2025',
    time: '10h',
    boost: null,
    caption: 'O que estao falando sobre O Amigo Secreto.',
    cta: 'Junte-se a eles - Link na bio',
    hashtags: ['#Depoimentos', '#AvaliacaoDeUsuarios', '#AmigoSecreto', '#AppAprovado', '#5Estrelas'],
    category: 'social-proof',
    month: 'dezembro',
    status: 'draft',
  },
  {
    id: 11,
    slug: 'countdown-natal',
    title: 'Countdown Natal',
    type: 'static',
    format: 'square',
    date: '21/12/2025',
    time: '12h',
    boost: 100,
    caption: 'Calma, ainda da tempo! Organize tudo em 2 minutos.',
    cta: 'Baixe agora - Link na bio',
    hashtags: ['#Natal2025', '#UltimaHora', '#AindaDaTempo', '#AmigoSecreto', '#Countdown'],
    category: 'seasonal',
    month: 'dezembro',
    status: 'draft',
  },
  {
    id: 12,
    slug: 'b2b-empresas',
    title: 'Para Empresas',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: 'ATENCAO RH:', subContent: 'Amigo Secreto da empresa nunca foi tao facil' },
      { id: 2, content: '10, 50, 100+ participantes.', subContent: 'O algoritmo da conta.' },
      { id: 3, content: 'Restricoes por departamento.', subContent: 'Ninguem tira o proprio chefe.' },
      { id: 4, content: 'Gratis. Sem limite de grupos. Sem limite de participantes.' },
    ],
    date: '22/12/2025',
    time: '10h',
    boost: 100,
    caption: 'Para RH e organizadores de confraternizacao.',
    cta: 'Marque seu RH! Link na bio para testar',
    hashtags: ['#RH', '#RecursosHumanos', '#Confraternizacao', '#B2B', '#GestaoDepessoas'],
    category: 'b2b',
    month: 'dezembro',
    status: 'draft',
  },

  // SEMANA 4: NATAL (24-27 DEZ)
  {
    id: 13,
    slug: 'feliz-natal',
    title: 'Feliz Natal',
    type: 'story',
    format: 'story',
    slides: [
      { id: 1, content: 'Feliz Natal!', subContent: 'Que seu Amigo Secreto seja perfeito' },
      { id: 2, content: 'Com ou sem o app...', subContent: 'Mas com o app e melhor' },
    ],
    date: '24/12/2025',
    time: '09h',
    boost: null,
    caption: 'Feliz Natal a todos!',
    cta: '',
    hashtags: ['#FelizNatal', '#Natal2025', '#OAmigoSecreto'],
    category: 'branding',
    month: 'dezembro',
    status: 'draft',
  },
  {
    id: 14,
    slug: 'ano-novo-dez',
    title: 'Ano Novo',
    type: 'static',
    format: 'square',
    date: '26/12/2025',
    time: '18h',
    boost: null,
    caption: 'O Amigo Secreto funciona o ano todo! Ja deixa o grupo criado pro proximo encontro.',
    cta: 'Crie seu grupo - Link na bio',
    hashtags: ['#AnoNovo2026', '#Reveillon', '#Confraternizacao', '#AmigoSecreto'],
    category: 'seasonal',
    month: 'dezembro',
    status: 'draft',
  },
  {
    id: 15,
    slug: 'retrospectiva',
    title: 'Retrospectiva',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: 'OBRIGADO!' },
      { id: 2, content: 'X downloads', subContent: 'X grupos criados' },
      { id: 3, content: 'Em 2026, ainda mais novidades.', subContent: 'Fique ligado!' },
    ],
    date: '27/12/2025',
    time: '12h',
    boost: null,
    caption: 'Obrigado a cada pessoa que baixou e confiou no app!',
    cta: 'Siga para novidades!',
    hashtags: ['#Obrigado', '#Comunidade', '#OAmigoSecreto', '#2026VemAi'],
    category: 'branding',
    month: 'dezembro',
    status: 'draft',
  },
  {
    id: 16,
    slug: 'ano-todo',
    title: 'O Ano Todo',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: 'Nao e so no Natal!', subContent: 'O Amigo Secreto funciona o ano todo' },
      { id: 2, content: 'Amigo Secreto', subContent: 'Dezembro' },
      { id: 3, content: 'Amigo Chocolate', subContent: 'Marco/Abril - Pascoa' },
      { id: 4, content: 'Amigo Caipira', subContent: 'Junho - Festa Junina' },
      { id: 5, content: 'Amigo Crianca', subContent: 'Outubro - Dia das Criancas' },
    ],
    date: '28/12/2025',
    time: '12h',
    boost: null,
    caption: 'O Amigo Secreto nao e so pro Natal! Use o app em diversas ocasioes ao longo do ano.',
    cta: 'Baixe o app - Link na bio',
    hashtags: ['#AmigoSecreto', '#AmigoChocolate', '#AmigoCaipira', '#AmigoCrianca', '#OAnoTodo'],
    category: 'seasonal',
    month: 'dezembro',
    status: 'draft',
  },

  // =============================================
  // JANEIRO 2026 - ANO NOVO, NOVAS CELEBRACOES
  // =============================================
  {
    id: 17,
    slug: 'feliz-ano-novo',
    title: 'Feliz Ano Novo',
    type: 'story',
    format: 'story',
    slides: [
      { id: 1, content: '2026 chegou!' },
      { id: 2, content: 'Obrigado por fazer parte da nossa historia' },
      { id: 3, content: 'Vem novidades por ai...' },
    ],
    date: '01/01/2026',
    time: '10h',
    boost: null,
    caption: 'Feliz Ano Novo! 2026 vem com muitas novidades.',
    cta: 'Link na bio',
    hashtags: ['#FelizAnoNovo', '#2026', '#OAmigoSecreto', '#AnoNovo'],
    category: 'branding',
    month: 'janeiro',
    status: 'draft',
  },
  {
    id: 18,
    slug: 'numeros-dezembro',
    title: 'Numeros de Dezembro',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: 'DEZEMBRO EM NÚMEROS' },
      { id: 2, content: '+5.000 SORTEIOS REALIZADOS' },
      { id: 3, content: '+2.000 GRUPOS CRIADOS' },
      { id: 4, content: '+10.000 MENSAGENS ANÔNIMAS' },
      { id: 5, content: '4.9/5 NOTA MÉDIA', subContent: 'Obrigado!' },
    ],
    date: '02/01/2026',
    time: '12h',
    boost: 50,
    caption: 'Ainda estamos em choque! Em menos de um mes voces fizeram historia com O Amigo Secreto.',
    cta: 'Baixe o app - Link na bio',
    hashtags: ['#OAmigoSecreto', '#Retrospectiva2025', '#Numeros', '#Sucesso', '#Obrigado'],
    category: 'social-proof',
    month: 'janeiro',
    status: 'draft',
  },
  {
    id: 19,
    slug: 'melhores-momentos',
    title: 'Melhores Momentos 2025',
    type: 'reels',
    format: 'story',
    slides: [
      { id: 1, content: 'Melhores Momentos 2025' },
      { id: 2, content: 'Lancamento do app' },
      { id: 3, content: 'Primeiros usuarios' },
      { id: 4, content: 'Reviews incriveis' },
    ],
    date: '04/01/2026',
    time: '18h',
    boost: null,
    caption: 'Uma retrospectiva dos melhores momentos do lancamento!',
    cta: 'Faca parte em 2026 - Link na bio',
    hashtags: ['#Retrospectiva', '#MelhoresMomentos', '#OAmigoSecreto', '#2025'],
    category: 'branding',
    month: 'janeiro',
    status: 'draft',
  },
  {
    id: 20,
    slug: 'amigo-ano-novo',
    title: 'Amigo Oculto de Ano Novo',
    type: 'static',
    format: 'square',
    date: '06/01/2026',
    time: '12h',
    boost: 50,
    caption: 'Nao conseguiu se reunir no Natal? Tranquilo! O Amigo Secreto funciona o ANO TODO.',
    cta: 'Crie seu grupo agora - Link na bio',
    hashtags: ['#AmigoOculto', '#AnoNovo2026', '#Reveillon', '#Confraternizacao', '#OAmigoSecreto'],
    category: 'seasonal',
    month: 'janeiro',
    status: 'draft',
  },
  {
    id: 21,
    slug: 'feature-badges',
    title: 'Feature: Sistema de Badges',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: 'CONQUISTE BADGES!' },
      { id: 2, content: 'Anfitriao Mestre', subContent: 'Criou 3+ grupos' },
      { id: 3, content: 'Enviador de Dicas', subContent: 'Mandou 10+ hints' },
      { id: 4, content: 'Rei do Chat', subContent: '100+ mensagens' },
      { id: 5, content: 'Mestre do Sorteio', subContent: 'Participou de 5+ sorteios' },
    ],
    date: '08/01/2026',
    time: '19h',
    boost: null,
    caption: 'Voce sabia que O Amigo Secreto tem um sistema de CONQUISTAS?',
    cta: 'Desbloqueie suas badges - Link na bio',
    hashtags: ['#Badges', '#Gamificacao', '#OAmigoSecreto', '#Conquistas', '#AppGratis'],
    category: 'feature',
    month: 'janeiro',
    status: 'draft',
  },
  {
    id: 22,
    slug: 'poll-badges',
    title: 'Poll: Qual badge voce conquistou?',
    type: 'story',
    format: 'story',
    slides: [
      { id: 1, content: 'Qual badge voce ja conquistou?' },
      { id: 2, content: 'Vote aqui!' },
    ],
    date: '10/01/2026',
    time: '12h',
    boost: null,
    caption: 'Conta pra gente nos comentarios!',
    cta: '',
    hashtags: ['#Poll', '#Badges', '#OAmigoSecreto'],
    category: 'engagement',
    month: 'janeiro',
    status: 'draft',
  },
  {
    id: 23,
    slug: 'depoimentos-janeiro',
    title: 'Depoimentos Reais',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: 'O QUE DIZEM NOSSOS USUÁRIOS' },
      { id: 2, content: '"O melhor app de amigo secreto!"', subContent: '⭐⭐⭐⭐⭐ Maria S.' },
      { id: 3, content: '"Finalmente acabou a bagunça de papelzinho!"', subContent: '⭐⭐⭐⭐⭐ João P.' },
      { id: 4, content: '"Usei na empresa e foi SUCESSO!"', subContent: '⭐⭐⭐⭐⭐ Ana C.' },
      { id: 5, content: 'FAÇA PARTE DESSA HISTÓRIA', subContent: 'Baixe grátis!' },
    ],
    date: '13/01/2026',
    time: '10h',
    boost: 50,
    caption: 'Depoimentos REAIS de usuarios do Natal 2025.',
    cta: 'Baixe e faca parte - Link na bio',
    hashtags: ['#Depoimentos', '#Reviews', '#5Estrelas', '#OAmigoSecreto', '#Recomendo'],
    category: 'social-proof',
    month: 'janeiro',
    status: 'draft',
  },
  {
    id: 24,
    slug: 'tutorial-chat',
    title: 'Tutorial: Chat Anonimo',
    type: 'reels',
    format: 'story',
    slides: [
      { id: 1, content: 'Voce sabia que pode conversar com seu amigo secreto?' },
      { id: 2, content: 'SEM revelar quem voce e!' },
      { id: 3, content: 'Demonstracao do chat' },
      { id: 4, content: 'CTA' },
    ],
    date: '15/01/2026',
    time: '18h',
    boost: null,
    caption: 'Tutorial: Como usar o chat anonimo do app.',
    cta: 'Experimente - Link na bio',
    hashtags: ['#Tutorial', '#ChatAnonimo', '#OAmigoSecreto', '#Dica'],
    category: 'feature',
    month: 'janeiro',
    status: 'draft',
  },
  {
    id: 25,
    slug: 'qa-janeiro',
    title: 'Q&A: Duvidas sobre o app',
    type: 'story',
    format: 'story',
    slides: [
      { id: 1, content: 'Tem duvidas sobre o app?' },
      { id: 2, content: 'Manda aqui!' },
    ],
    date: '17/01/2026',
    time: '12h',
    boost: null,
    caption: 'Responderemos todas as duvidas!',
    cta: '',
    hashtags: ['#QeA', '#Duvidas', '#OAmigoSecreto'],
    category: 'engagement',
    month: 'janeiro',
    status: 'draft',
  },
  {
    id: 26,
    slug: 'feature-dicas',
    title: 'Feature: Sistema de Dicas',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: 'SISTEMA DE DICAS' },
      { id: 2, content: 'De dicas anonimas sobre voce' },
      { id: 3, content: 'Receba dicas do seu amigo secreto' },
      { id: 4, content: 'Crie expectativa ate a revelacao' },
      { id: 5, content: 'A diversao dura o mes inteiro!' },
    ],
    date: '20/01/2026',
    time: '12h',
    boost: null,
    caption: 'A melhor parte do amigo secreto e o MISTERIO!',
    cta: 'Experimente - Link na bio',
    hashtags: ['#Dicas', '#Hints', '#AmigoSecreto', '#Misterio', '#Surpresa'],
    category: 'feature',
    month: 'janeiro',
    status: 'draft',
  },
  {
    id: 27,
    slug: 'dica-wishlist',
    title: 'Dica do Dia: Wishlist',
    type: 'static',
    format: 'square',
    date: '22/01/2026',
    time: '19h',
    boost: null,
    caption: 'Dica: Use a wishlist para nunca mais errar o presente!',
    cta: 'Crie sua wishlist - Link na bio',
    hashtags: ['#DicaDoDia', '#Wishlist', '#OAmigoSecreto', '#Presente'],
    category: 'feature',
    month: 'janeiro',
    status: 'draft',
  },
  {
    id: 28,
    slug: 'enquete-feature',
    title: 'Enquete: Feature mais usada',
    type: 'story',
    format: 'story',
    slides: [
      { id: 1, content: 'Qual feature voce mais usa?' },
      { id: 2, content: 'Chat? Wishlist? Badges?' },
    ],
    date: '24/01/2026',
    time: '12h',
    boost: null,
    caption: 'Conta pra gente!',
    cta: '',
    hashtags: ['#Enquete', '#Features', '#OAmigoSecreto'],
    category: 'engagement',
    month: 'janeiro',
    status: 'draft',
  },
  {
    id: 29,
    slug: 'pov-descoberta',
    title: 'POV: Descobrindo seu amigo secreto',
    type: 'reels',
    format: 'story',
    slides: [
      { id: 1, content: 'POV: Voce abre o app...' },
      { id: 2, content: 'E descobre quem te tirou...' },
      { id: 3, content: 'Reacao!' },
    ],
    date: '26/01/2026',
    time: '18h',
    boost: null,
    caption: 'Quem ja teve essa reacao? Marca nos comentarios!',
    cta: 'Baixe o app - Link na bio',
    hashtags: ['#POV', '#AmigoSecreto', '#Reacao', '#Viral', '#OAmigoSecreto'],
    category: 'engagement',
    month: 'janeiro',
    status: 'draft',
  },
  {
    id: 30,
    slug: 'janeiro-review',
    title: 'Janeiro em Review',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: 'JANEIRO EM REVIEW' },
      { id: 2, content: 'Novos usuarios' },
      { id: 3, content: 'Novos grupos' },
      { id: 4, content: 'Fevereiro vem ai!' },
    ],
    date: '29/01/2026',
    time: '12h',
    boost: null,
    caption: 'Obrigado por mais um mes incrivel!',
    cta: 'Siga para novidades!',
    hashtags: ['#JaneiroEmReview', '#OAmigoSecreto', '#Retrospectiva'],
    category: 'branding',
    month: 'janeiro',
    status: 'draft',
  },

  // =============================================
  // FEVEREIRO 2026 - FOLIA E AMIZADE
  // =============================================
  {
    id: 31,
    slug: 'teaser-carnaval',
    title: 'Teaser Carnaval',
    type: 'story',
    format: 'story',
    slides: [
      { id: 1, content: 'Carnaval vem ai...' },
      { id: 2, content: 'E a gente tem uma ideia!' },
    ],
    date: '01/02/2026',
    time: '12h',
    boost: null,
    caption: 'Carnaval vem ai! Fique ligado.',
    cta: '',
    hashtags: ['#Carnaval2026', '#OAmigoSecreto', '#EmBreve'],
    category: 'teaser',
    month: 'fevereiro',
    status: 'draft',
  },
  {
    id: 32,
    slug: 'amigo-folia',
    title: 'Amigo Folia: Carnaval Edition',
    type: 'static',
    format: 'square',
    date: '02/02/2026',
    time: '10h',
    boost: 75,
    caption: 'AMIGO FOLIA! Quem disse que amigo secreto e so no Natal? No Carnaval, organize um amigo secreto tematico!',
    cta: 'Crie seu grupo - Link na bio',
    hashtags: ['#AmigoFolia', '#Carnaval2026', '#BlocoDeRua', '#AmigoSecreto', '#Folia'],
    category: 'seasonal',
    month: 'fevereiro',
    status: 'draft',
  },
  {
    id: 33,
    slug: 'ideias-carnaval',
    title: '5 Ideias de Presente de Carnaval',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: '5 IDEIAS DE PRESENTE DE CARNAVAL' },
      { id: 2, content: 'Fantasia criativa' },
      { id: 3, content: 'Kit de sobrevivencia', subContent: 'protetor, agua, glitter' },
      { id: 4, content: 'Acessorios de bloco' },
      { id: 5, content: 'Playlist personalizada' },
    ],
    date: '04/02/2026',
    time: '12h',
    boost: null,
    caption: 'Salve essas ideias para o Amigo Folia!',
    cta: 'Use a wishlist do app - Link na bio',
    hashtags: ['#IdeiasDePresente', '#Carnaval2026', '#AmigoFolia', '#OAmigoSecreto'],
    category: 'seasonal',
    month: 'fevereiro',
    status: 'draft',
  },
  {
    id: 34,
    slug: 'poll-carnaval',
    title: 'Poll: Vai pular carnaval?',
    type: 'story',
    format: 'story',
    slides: [
      { id: 1, content: 'Vai pular carnaval?' },
      { id: 2, content: 'Sim / Nao / Talvez' },
    ],
    date: '06/02/2026',
    time: '12h',
    boost: null,
    caption: 'Conta pra gente!',
    cta: '',
    hashtags: ['#Poll', '#Carnaval2026', '#OAmigoSecreto'],
    category: 'engagement',
    month: 'fevereiro',
    status: 'draft',
  },
  {
    id: 35,
    slug: 'team-building',
    title: 'Team Building B2B',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: 'TEAM BUILDING diferente' },
      { id: 2, content: 'Amigo secreto fora do Natal? SIM!' },
      { id: 3, content: 'Promove integracao entre equipes' },
      { id: 4, content: 'Funciona com qualquer tamanho de equipe' },
      { id: 5, content: '100% gratis para empresas' },
    ],
    date: '09/02/2026',
    time: '10h',
    boost: 75,
    caption: 'RH, essa e pra voces! Use amigo secreto como ferramenta de Team Building.',
    cta: 'Marque seu RH - Link na bio',
    hashtags: ['#TeamBuilding', '#RH', '#GestaoDepessoas', '#RecursosHumanos', '#Empresas'],
    category: 'b2b',
    month: 'fevereiro',
    status: 'draft',
  },
  {
    id: 36,
    slug: 'case-empresa',
    title: 'Case: Empresa que usou o app',
    type: 'reels',
    format: 'story',
    slides: [
      { id: 1, content: 'Case de sucesso' },
      { id: 2, content: 'Empresa X usou o app' },
      { id: 3, content: 'Resultado incrivel' },
    ],
    date: '11/02/2026',
    time: '18h',
    boost: null,
    caption: 'Veja como empresas estao usando O Amigo Secreto!',
    cta: 'Experimente na sua empresa - Link na bio',
    hashtags: ['#CaseDeSucesso', '#B2B', '#OAmigoSecreto', '#Empresas'],
    category: 'b2b',
    month: 'fevereiro',
    status: 'draft',
  },
  {
    id: 37,
    slug: 'guia-rh',
    title: 'Para RH: Guia de confraternizacao',
    type: 'story',
    format: 'story',
    slides: [
      { id: 1, content: 'Guia para RH' },
      { id: 2, content: 'Como organizar confraternizacao' },
      { id: 3, content: 'Link para download' },
    ],
    date: '13/02/2026',
    time: '12h',
    boost: null,
    caption: 'RH, baixe nosso guia gratuito!',
    cta: 'Link na bio',
    hashtags: ['#RH', '#Guia', '#Confraternizacao', '#OAmigoSecreto'],
    category: 'b2b',
    month: 'fevereiro',
    status: 'draft',
  },
  {
    id: 38,
    slug: 'dia-dos-amigos',
    title: 'Dia dos Amigos',
    type: 'static',
    format: 'square',
    date: '14/02/2026',
    time: '10h',
    boost: null,
    caption: 'Hoje e Dia dos NAMORADOS... mas tambem e dia de celebrar a AMIZADE! Amigos sao a familia que escolhemos.',
    cta: 'Crie um grupo com seus amigos - Link na bio',
    hashtags: ['#DiadosAmigos', '#Amizade', '#BFF', '#AmigoSecreto', '#Celebracao'],
    category: 'seasonal',
    month: 'fevereiro',
    status: 'draft',
  },
  {
    id: 39,
    slug: 'revelacoes-carnaval',
    title: 'Compilacao: Revelacoes de Carnaval',
    type: 'reels',
    format: 'story',
    slides: [
      { id: 1, content: 'Revelacoes de Carnaval' },
      { id: 2, content: 'UGC compilation' },
    ],
    date: '16/02/2026',
    time: '18h',
    boost: null,
    caption: 'Os melhores momentos do Amigo Folia!',
    cta: 'Marque a gente nas suas revelacoes!',
    hashtags: ['#AmigoFolia', '#Carnaval2026', '#Revelacao', '#OAmigoSecreto'],
    category: 'ugc',
    month: 'fevereiro',
    status: 'draft',
  },
  {
    id: 40,
    slug: 'ugc-carnaval',
    title: 'UGC: Mostre seu grupo',
    type: 'story',
    format: 'story',
    slides: [
      { id: 1, content: 'Mostre seu grupo de carnaval!' },
      { id: 2, content: 'Use #OAmigoSecreto' },
    ],
    date: '18/02/2026',
    time: '12h',
    boost: null,
    caption: 'Queremos ver seus grupos! Use a hashtag.',
    cta: '',
    hashtags: ['#UGC', '#OAmigoSecreto', '#Carnaval2026'],
    category: 'ugc',
    month: 'fevereiro',
    status: 'draft',
  },
  {
    id: 41,
    slug: 'melhores-carnaval',
    title: 'Melhores Momentos Carnaval',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: 'MELHORES MOMENTOS CARNAVAL' },
      { id: 2, content: 'Momento 1' },
      { id: 3, content: 'Momento 2' },
      { id: 4, content: 'Momento 3' },
    ],
    date: '23/02/2026',
    time: '10h',
    boost: null,
    caption: 'Os melhores momentos do Carnaval 2026!',
    cta: 'Marque quem pulou carnaval com voce!',
    hashtags: ['#Carnaval2026', '#MelhoresMomentos', '#OAmigoSecreto'],
    category: 'branding',
    month: 'fevereiro',
    status: 'draft',
  },
  {
    id: 42,
    slug: 'volta-rotina',
    title: 'Volta a Rotina',
    type: 'static',
    format: 'square',
    date: '25/02/2026',
    time: '12h',
    boost: null,
    caption: 'Carnaval acabou, mas a diversao continua! Crie grupos para proximas celebracoes.',
    cta: 'Link na bio',
    hashtags: ['#VoltaARotina', '#PosCarnaval', '#OAmigoSecreto'],
    category: 'seasonal',
    month: 'fevereiro',
    status: 'draft',
  },
  {
    id: 43,
    slug: 'teaser-pascoa',
    title: 'Teaser: Pascoa vem ai',
    type: 'story',
    format: 'story',
    slides: [
      { id: 1, content: 'Pascoa vem ai...' },
      { id: 2, content: 'Amigo Chocolate!' },
    ],
    date: '27/02/2026',
    time: '12h',
    boost: null,
    caption: 'Amigo Chocolate vem ai!',
    cta: '',
    hashtags: ['#Pascoa2026', '#AmigoChocolate', '#OAmigoSecreto'],
    category: 'teaser',
    month: 'fevereiro',
    status: 'draft',
  },
  {
    id: 44,
    slug: 'tutorial-restricoes',
    title: 'Tutorial: Algoritmo de Restricoes',
    type: 'reels',
    format: 'story',
    slides: [
      { id: 1, content: 'Tutorial: Restricoes' },
      { id: 2, content: 'Como definir quem nao pode tirar quem' },
      { id: 3, content: 'Demonstracao' },
    ],
    date: '28/02/2026',
    time: '18h',
    boost: null,
    caption: 'Aprenda a usar as restricoes do app!',
    cta: 'Experimente - Link na bio',
    hashtags: ['#Tutorial', '#Restricoes', '#OAmigoSecreto', '#Algoritmo'],
    category: 'feature',
    month: 'fevereiro',
    status: 'draft',
  },

  // =============================================
  // MARCO 2026 - MULHERES QUE INSPIRAM + PASCOA
  // =============================================
  {
    id: 45,
    slug: 'mulheres-organizam',
    title: 'Mulheres que Organizam Celebracoes',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: 'AS ORGANIZADORAS' },
      { id: 2, content: '78% dos grupos sao criados por mulheres' },
      { id: 3, content: 'Maes que reunem a familia' },
      { id: 4, content: 'Amigas que mantem o grupo unido' },
      { id: 5, content: 'Profissionais de RH', subContent: 'Obrigado por fazer acontecer!' },
    ],
    date: '02/03/2026',
    time: '10h',
    boost: 100,
    caption: 'Voces sao incriveis! 78% dos grupos sao criados e organizados por MULHERES.',
    cta: 'Obrigado por escolher O Amigo Secreto',
    hashtags: ['#DiaInternacionalDaMulher', '#Mulheres', '#Organizadoras', '#OAmigoSecreto'],
    category: 'branding',
    month: 'marco',
    status: 'draft',
  },
  {
    id: 46,
    slug: 'countdown-mulher',
    title: 'Countdown Dia da Mulher',
    type: 'story',
    format: 'story',
    slides: [
      { id: 1, content: '8 de Marco' },
      { id: 2, content: 'Dia Internacional da Mulher' },
    ],
    date: '05/03/2026',
    time: '12h',
    boost: null,
    caption: 'Faltam 3 dias!',
    cta: '',
    hashtags: ['#8DeMarco', '#DiaDaMulher', '#Countdown'],
    category: 'seasonal',
    month: 'marco',
    status: 'draft',
  },
  {
    id: 47,
    slug: 'dia-mulher',
    title: 'Feliz Dia Internacional da Mulher',
    type: 'static',
    format: 'square',
    date: '08/03/2026',
    time: '09h',
    boost: 50,
    caption: 'Feliz Dia Internacional da Mulher! A todas as mulheres que fazem as celebracoes acontecerem.',
    cta: '',
    hashtags: ['#8DeMarco', '#DiaInternacionalDaMulher', '#Mulheres', '#Empoderamento'],
    category: 'branding',
    month: 'marco',
    status: 'draft',
  },
  {
    id: 48,
    slug: 'amigo-chocolate',
    title: 'Amigo Chocolate: Como Funciona',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: 'AMIGO CHOCOLATE' },
      { id: 2, content: 'A versao de Pascoa do amigo secreto!' },
      { id: 3, content: 'Todo mundo troca chocolates' },
      { id: 4, content: 'Use a wishlist para sugerir marcas' },
      { id: 5, content: 'Organize sua Pascoa!' },
    ],
    date: '09/03/2026',
    time: '12h',
    boost: 75,
    caption: 'Ja ouviu falar em AMIGO CHOCOLATE? E a versao de Pascoa do amigo secreto!',
    cta: 'Crie seu grupo - Link na bio',
    hashtags: ['#AmigoChocolate', '#Pascoa2026', '#TrocaDeChocolates', '#OAmigoSecreto'],
    category: 'seasonal',
    month: 'marco',
    status: 'draft',
  },
  {
    id: 49,
    slug: 'ideias-pascoa',
    title: 'Ideias de Presente de Pascoa',
    type: 'reels',
    format: 'story',
    slides: [
      { id: 1, content: 'Ideias de Presente de Pascoa' },
      { id: 2, content: 'Trufas' },
      { id: 3, content: 'Ovos de Pascoa' },
      { id: 4, content: 'Barras gourmet' },
    ],
    date: '12/03/2026',
    time: '18h',
    boost: null,
    caption: 'Ideias de presente para o Amigo Chocolate!',
    cta: 'Adicione na wishlist - Link na bio',
    hashtags: ['#IdeiasDePresente', '#Pascoa2026', '#AmigoChocolate', '#Chocolates'],
    category: 'seasonal',
    month: 'marco',
    status: 'draft',
  },
  {
    id: 50,
    slug: 'poll-chocolate',
    title: 'Poll: Vai fazer Amigo Chocolate?',
    type: 'story',
    format: 'story',
    slides: [
      { id: 1, content: 'Vai fazer Amigo Chocolate?' },
      { id: 2, content: 'Sim / Nao / Talvez' },
    ],
    date: '14/03/2026',
    time: '12h',
    boost: null,
    caption: 'Conta pra gente!',
    cta: '',
    hashtags: ['#Poll', '#AmigoChocolate', '#Pascoa2026'],
    category: 'engagement',
    month: 'marco',
    status: 'draft',
  },
  {
    id: 51,
    slug: 'nova-feature',
    title: 'Nova Feature',
    type: 'static',
    format: 'square',
    date: '16/03/2026',
    time: '12h',
    boost: null,
    caption: 'Nova funcionalidade chegando!',
    cta: 'Atualize o app - Link na bio',
    hashtags: ['#NovaFeature', '#Update', '#OAmigoSecreto'],
    category: 'feature',
    month: 'marco',
    status: 'draft',
  },
  {
    id: 52,
    slug: 'dicas-uso',
    title: 'Dicas de Uso que Voce Nao Sabia',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: '5 DICAS que voce nao sabia' },
      { id: 2, content: 'QR Code para convite rapido' },
      { id: 3, content: 'Restricoes multiplas no mesmo grupo' },
      { id: 4, content: 'Wishlist com links diretos' },
      { id: 5, content: 'Chat anonimo com hints' },
    ],
    date: '18/03/2026',
    time: '12h',
    boost: null,
    caption: 'Dicas que voce provavelmente nao sabia!',
    cta: 'Domine o app - Link na bio',
    hashtags: ['#Dicas', '#Tips', '#OAmigoSecreto', '#TruquesDoApp'],
    category: 'feature',
    month: 'marco',
    status: 'draft',
  },
  {
    id: 53,
    slug: 'qa-marco',
    title: 'Q&A com a Equipe',
    type: 'story',
    format: 'story',
    slides: [
      { id: 1, content: 'Perguntas para a equipe?' },
      { id: 2, content: 'Manda aqui!' },
    ],
    date: '20/03/2026',
    time: '12h',
    boost: null,
    caption: 'Responderemos ao vivo!',
    cta: '',
    hashtags: ['#QeA', '#Equipe', '#OAmigoSecreto'],
    category: 'engagement',
    month: 'marco',
    status: 'draft',
  },
  {
    id: 54,
    slug: 'pov-chocolate',
    title: 'POV: Revelacao de Amigo Chocolate',
    type: 'reels',
    format: 'story',
    slides: [
      { id: 1, content: 'POV: Voce descobre...' },
      { id: 2, content: 'Que seu amigo chocolate...' },
      { id: 3, content: 'Te deu o melhor chocolate!' },
    ],
    date: '22/03/2026',
    time: '18h',
    boost: null,
    caption: 'Quem ja teve essa felicidade?',
    cta: 'Baixe o app - Link na bio',
    hashtags: ['#POV', '#AmigoChocolate', '#Revelacao', '#Pascoa2026'],
    category: 'engagement',
    month: 'marco',
    status: 'draft',
  },
  {
    id: 55,
    slug: 'countdown-pascoa',
    title: 'Countdown Pascoa',
    type: 'carousel',
    format: 'square',
    slides: [
      { id: 1, content: 'COUNTDOWN PASCOA' },
      { id: 2, content: 'Faltam X dias!' },
      { id: 3, content: 'Ja criou seu grupo?' },
      { id: 4, content: 'Ainda da tempo!' },
    ],
    date: '23/03/2026',
    time: '10h',
    boost: 50,
    caption: 'Pascoa chegando! Ja criou seu grupo de Amigo Chocolate?',
    cta: 'Crie agora - Link na bio',
    hashtags: ['#Countdown', '#Pascoa2026', '#AmigoChocolate', '#OAmigoSecreto'],
    category: 'seasonal',
    month: 'marco',
    status: 'draft',
  },
  {
    id: 56,
    slug: 'ultimas-dicas-pascoa',
    title: 'Ultimas Dicas antes da Pascoa',
    type: 'story',
    format: 'story',
    slides: [
      { id: 1, content: 'Ultimas dicas!' },
      { id: 2, content: 'Antes da Pascoa' },
      { id: 3, content: 'Nao esqueca de...' },
    ],
    date: '26/03/2026',
    time: '12h',
    boost: null,
    caption: 'Ultimas dicas antes da Pascoa!',
    cta: '',
    hashtags: ['#Dicas', '#Pascoa2026', '#AmigoChocolate'],
    category: 'seasonal',
    month: 'marco',
    status: 'draft',
  },
  {
    id: 57,
    slug: 'tutorial-pascoa',
    title: 'Tutorial: Grupo de Pascoa em 1 min',
    type: 'reels',
    format: 'story',
    slides: [
      { id: 1, content: 'Crie um grupo de Pascoa' },
      { id: 2, content: 'Em menos de 1 minuto!' },
      { id: 3, content: 'Demonstracao rapida' },
    ],
    date: '29/03/2026',
    time: '18h',
    boost: 50,
    caption: 'Tutorial rapido: Como criar um grupo de Amigo Chocolate em menos de 1 minuto!',
    cta: 'Baixe o app - Link na bio',
    hashtags: ['#Tutorial', '#AmigoChocolate', '#Pascoa2026', '#Em1Minuto'],
    category: 'feature',
    month: 'marco',
    status: 'draft',
  },
  {
    id: 58,
    slug: 'ultima-chamada-chocolate',
    title: 'Ultima Chamada Amigo Chocolate',
    type: 'static',
    format: 'square',
    date: '31/03/2026',
    time: '10h',
    boost: null,
    caption: 'ULTIMA CHAMADA! Pascoa e essa semana. Ja criou seu grupo de Amigo Chocolate?',
    cta: 'Crie agora - Link na bio',
    hashtags: ['#UltimaChamada', '#AmigoChocolate', '#Pascoa2026', '#OAmigoSecreto'],
    category: 'seasonal',
    month: 'marco',
    status: 'draft',
  },
];

// Helper functions
export const getPostById = (id: number): PostData | undefined => {
  return posts.find(post => post.id === id);
};

export const getPostBySlug = (slug: string): PostData | undefined => {
  return posts.find(post => post.slug === slug);
};

export const getPostsByCategory = (category: PostData['category']): PostData[] => {
  return posts.filter(post => post.category === category);
};

export const getPostsByMonth = (month: PostMonth): PostData[] => {
  return posts.filter(post => post.month === month);
};

export const getPostsByStatus = (status: PostStatus): PostData[] => {
  return posts.filter(post => post.status === status);
};

export const getPostsByType = (type: PostType): PostData[] => {
  return posts.filter(post => post.type === type);
};

export const getBoostedPosts = (): PostData[] => {
  return posts.filter(post => post.boost !== null);
};

export const getTotalBudget = (): number => {
  return posts.reduce((sum, post) => sum + (post.boost || 0), 0);
};

export const getBudgetByMonth = (month: PostMonth): number => {
  return posts
    .filter(post => post.month === month)
    .reduce((sum, post) => sum + (post.boost || 0), 0);
};
